# Deployment for Ktor application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdochub-deployment
  namespace: kdochub-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kdochub
  template:
    metadata:
      labels:
        app: kdochub
    spec:
      containers:
        - name: kdochub
          image: kdochub-image:latest
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 5005
          env:
            - name: JAVA_OPTS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: KDOCHUB_KTOR_SECURITY_SSL_KEY_STORE
              value: "/app/keystore.p12"
