apiVersion: v1
kind: Service
metadata:
  name: dochub-service
  namespace: dochub-project
spec:
  selector:
    app: dochub
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 8443
      targetPort: 8443
    - protocol: TCP
      port: 5005
      targetPort: 5005
  type: NodePort
